import ToastProvider from "@/providers/toast-provider";
import React from "react";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Npm Trends",
  description: "Generated by Next.js",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastProvider />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
