import "@/styles/globals.css";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

export default function Dashboard({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div>
        <main className="h-full  p-10">{children}</main>
      </div>
    </div>
  );
}
